### ISSUE TITLE
Does the tool allow minimal action ?

### ISSUE THREAD

**Issue by manish211** [SoftwareEngineeringToolDemos/FSE-2013-Jalangi#4]
The user has to open the terminal manually and type the commands manually by following the steps. Feel free to close this issue with appropriate comments if you feel nothing can be automated.

**Comment by jalanmiddleton** [comment]
I initially tried to leave an open terminal with the pre-filled commands, but losing the save state when converting to .ova meant losing that too. I've been looking into showing a terminal with a pre-filled (but not yet executed) command but nothing has come of it yet. 

I'll still look to see if there are any other automatic options, but in the worst case, I can try to autoshow a text file instructing the user to copy-and-paste the simplest command and have an auto-loaded terminal ready, if it's not too awkward.

**Comment by manish211** [comment]
I am not sure...if you can just put the commands in the shell script and load the shell script, it could help
