### ISSUE TITLE
Did not find link to original video

### ISSUE THREAD

**Issue by manish211** [SoftwareEngineeringToolDemos/FSE-2013-Jalangi#7]
I did not find link to the original video of the the tool for demo in the readme file.

**Comment by jalanmiddleton** [comment]
I don't know of any video that show the command-line interface through video, but one was provided for the Tizen IDE plug-in. This, though, is hidden in some of the README.md text. I duplicated the link down in my portion of the README and clarified the availability of this plug-in.
